function getProjectData(projectName) {
    if (projectName == 'mememachine') {
        return {skills: 'Python, Python Reddit Aggregator Wrapper (PRAW), ImgurPython', title: 'Meme Machine', longDescription: 'The Association for Computing Machinery, University of the Pacific chapter created a project in March 2017 that downloads and aggregates memes from various social media sites including Reddit, Imgur, Tumblr, and Imgflip using Python and Haskell. It included a plan to write a module that would gather ratings and use the data as input for machine learning to create its own memes.', links: [{title: 'GitHub Repository', href: 'https://github.com/uopacm/mememachinecollector'}], embeds: []};
    } else if (projectName == 'shutin') {
        return {skills: 'Final Cut Pro X, Adobe Premiere Pro, Foley Art, Lighting Setup', title: 'Shut In', longDescription: 'The San Joaquin County Office of Education held a two-week filmmaking workshop in June 2012. After a full day of shooting at a daycare in Manteca, CA, the crew premiered the film at the Lincoln High School theatre to a packed house. The crew then held a Q and A session with those in attendance.', links: [{title: 'IMDB Link', href: 'https://www.imdb.com/title/tt2644836/'}], embeds: ['https://www.youtube.com/embed/1g2i2bYbwC8']};
    } else if (projectName == 'bulletrush') {
        return {skills: 'Unity, C#, Project Management, Agile Development', title: 'Bullet Rush', longDescription: 'I took the Computer Game Technologies course at University of the Pacific in Fall 2019 to learn Video Game Design and Development. After pitching ideas to the class similarly to my earlier Application Development course, I was placed as the Project Manager of the Bullet Rush team along with a Lead Programmer, a general Programmer, and a Media Director. At the end of the course, we presented to the community for feedback.', links: [{title: 'Bitbucket Repository', href: 'https://bitbucket.org/jacob5567/bullet-rush'}], embeds: []};
    } else if (projectName == 'dndcombatsim') {
        return {skills: 'Java, JavaScript, Project Management', title: 'Dungeons and Dragons Combat Simulator', longDescription: 'I took the Application Development course at University of the Pacific to learn how to work on a team to develop an application. In our groups, we proposed our final projects for the class and began our work. There were no roles, so I took initiative to be the Project Manager along with doing basic coding on the JSON data and general backend programming.', links: [{title: 'Because we used data from 5e.tools, I am not including a link to the repository here.', href: ''}], embeds: []};
    } else if (projectName == 'cansat') {
        return {skills: 'C++, Arduino', title: 'CanSat', longDescription: 'During my junior year of high school, my dad approached me with an offer to work on a project involving a simulated sattelite in an enclosure the size and shape of a soda can run by an Arduino. He connected me and two of his students to Ted Tagami of Magnitude.io and we were all connected with Dr. Elizabeth Basha and her students at University of the Pacific. The CanSat project was eventually launched into low-Earth orbit in November 2019.', links: [{title: 'More Information', href: 'https://magnitude.io/cansat-stem-education/'}], embeds: []};
    } else if (projectName == 'fourwoods') {
        return {skills: 'Adobe Audition, Scriptwriting, Directing for Voiceover', title: 'The Four Woods Podcast', longDescription: 'The Four Woods Podcast, part of my senior project for my Media X degree at University of the Pacific, is an audio drama podcast about Ross Hansen, a 16-year-old kid who attends magical high school for the first time in his life after meeting his parents who he hasn\'t seen for thirteen years. A pilot episode of the podcast is currently available wherever you get your podcasts with more on the way in the coming months.', links: [{title: 'Anchor.FM Page', href: 'https://anchor.fm/4woodspodcast'}, {title: 'Apple Podcasts Page', href: 'https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy81MjAwNTY0OC9wb2RjYXN0L3Jzcw=='}, {title: 'Amazon Music', href: 'https://music.amazon.com/podcasts/12dfc842-f2c5-42cd-9989-e43d1ac19e54/The-Four-Woods'}, {title: 'Stitcher', href: 'https://www.stitcher.com/show/the-four-woods'}, {title: 'Breaker', href: 'https://www.breaker.audio/p/the-four-woods'}, {title: 'Pocket Casts', href: 'https://pca.st/kexc4wrj'}], embeds: []};
    } else {
        return {};
    }
}

export default getProjectData;